name: Deploy Vite React App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy files to server
        uses: actions/ftp-deploy@v2
        with:
          server: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          local_dir: ./dist
          remote_dir: /var/www/frontend

      - name: Restart Web Server (Optional)
        run: ssh ${{ secrets.SERVER_USER }}@$${{ secrets.SERVER_IP }} 'sudo systemctl restart nginx'
